### PR TITLE
Iconfont

### PR DESCRIPTION
**Pull request by anitagraham**
Use the Font-Awesome iconfont instead of individual icon files.

**SCSS and appearance changes**
* Use SCSS partials and `@import` them.
* Implement long-lost login spinner 
* Snug page-part controls up to top border
* Basic CSS changes to use icons.
* Icons all grey (#888) except for Delete and Error icons (red)
* Add fonts to vendor: the font used is a cut-down version of fontAwesome with just the icons used by Refinery (and a couple more that might be needed). *See list at end*
* Add sort down, sortup icons (although not yet used as a class)
* Make draft page check box float to the right

**Changes in views to use iconfont**
* Add `action_icon` and `action_label` methods in tag_helper.rb. Display an action with either an icon or label.
* Change action `link_to`s to call `action_icon` or `action_label`

**Changes in specs to accomodate icon use**
* Trigger clicks on links which poltergeist can’t see
* Make locale marker tests see the new markers

**Other**
* Change generators to use `action_label` and `action_icon`

**Icons in fontfiles**
The icons were taken from [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/). [Icomoon](https://icomoon.io/app/#/select) was used to select the following icons and create fonts with them.
arrow-circle-o-down
arrow-circle-o-up
arrows-h
arrows-v
check
check-circle
check-circle-o
check-square-o
close
cog
cogs
comment
comment-o
download
edit
envelope
envelope-o
exchange
exclamation-circle
exclamation-triangle
eye
file
file-archive-o
file-audio-o
file-code-o
file-excel-o
file-image-o
file-movie-o
file-o
file-pdf-o
file-powerpoint-o
file-text
file-text-o
file-word-o
folder
folder-o
folder-open
folder-open-o
info-circle
minus-circle
plus-circle
question-circle
random
search
sort
spinner
th
th-list
times-circle
times-circle-o
trash-o
upload

### CODE REVIEW

**Comment by parndt** [comment]
Wow, great work.  Any chance of before/after screenshots so that we can look back on this as a reference for how it should look?

**Comment by anitagraham** [comment]
Will do

**Comment by anitagraham** [comment]
Before and after images were an exercise worth doing. There's at least one css fix to come. (it's in almost all the images).
Here are some before and after image pairs.
**Page Index**
pageindex
**Page Edit**
pageedit
**Image List View**
imagelistview
**Image Grid View**
imagegridview
**User Index**
userindex

**Resource Index**
resourceindex

**Comment by parndt** [comment]
The buttons on the right hand side now have a bunch of empty space on the left of the icon (previously this was because there was a background image and we padded it) which doesn't seem to make much sense anymore.. but I wonder what we can do about that?

**Comment by anitagraham** [comment]
I can fix that in css, but what happens then to extensions still using the icons?  I guess I just use more specific css for each of them. Does that sound OK? (I have done the basic fix, but not looked further into differentiating between icons and images.)

**Comment by parndt** [comment]
Yeah, that sounds good to me. Also I see what you mean about the bottom border being missing on the buttons!

**Comment by anitagraham** [comment]
Those css errors fixed. But hold the presses: I think the assets aren't loading properly. My test application happened to use font-awesome anyway. I've removed it from the gemfile and making sure the font is loading from vendor/assets. Sorry!

**Comment by anitagraham** [comment]
Here is a screenshot of Refinerycms-settings using both icon font and images. This seems to look OK.
Will keep adding extensions to see what happens.
setttings index

**Comment by bricesanchez** [comment]
Could you change grey icons for black icons ? It doesn't pass accessibility contrast test :

colour_contrast_analyser_and_60f9f746-c7e6-11e4-847b-01ec94807ea4_png__1085x651_

**Comment by gwagener** [comment]
Nice work! Does this reduce page load because of fewer assets? You say all the icons have gone grey except red ones, but there are also some blue info icons. I think I'd make them grey as well. Also, on the edit page it looks like you are creating/deleting/reordering titles rather than page parts because the buttons have moved up so far.

**Comment by anitagraham** [comment]
Icon colours are easy to change. I changed them last night to use #404650, which @parndt is using in another branch for the site bar.

Yes, don't know what to do about icon colours. My first screen shots had tertiary colours (rose, azure, violet etc) for the icons but I thought it might look better in grey except warnings. And information blue is a standard of a sort.

Discussion and guidance welcome. Also, the colours are set in core/app/assets/stylesheets/_colours.scss so it's easy to change them. I'll change the info icon colour to grey too and  move those icons up again. (I fixed it, but may have lost the fix during rebase).

Page Load time: does seem reduced. Enough that I notice/saw the page-branch gifs loading and taking a long time. They *could* be done with svg or icons too, I suppose, but I've never really looked at how they work in detail.

**Comment by anitagraham** [comment]
There are so many blues on the page! Side menu & search button, page icons, action backgrounds.
I've changed all except the menu bar highlight colour (and search button) to be related to the blue font colour in the page menu.

coordinated blues

Grey action panels. 
grey action panels

**Comment by anitagraham** [comment]
The overlap problem seems to come with the combination of poltergeist and css pseudo-elements (such as before::).
I guess I can change them to `node.trigger(:click)`.

**Comment by parndt** [comment]
@anitagraham is this ready to go?

**Comment by anitagraham** [comment]
Yes. It doesn't include #2919. Should it?

**Comment by parndt** [comment]
No that's fine

**Comment by parndt** [comment]
Feedback:

Text shadowing makes it a bit hard to read on hover:
screen shot 2015-03-23 at 11 50 21

**Comment by anitagraham** [comment]
OK. This time, on hover, I'm changing the font-size to 1.3rem. (Default is 1.2).
I also bit the bullet and included all of font-awesome. The woff/woff2 files are 74K/54K compared to 30K for a reduced set of icons.  

This will mean that other icons can gradually be included without changing the font files.
All the normal editor icons are included, so it might be worthwhile using the icons with wymeditor.

**Comment by anitagraham** [comment]
I guess I should rebase and squash about now...

**Comment by parndt** [comment]
I didn't want to ask :smile: but yes

**Comment by simi** [comment]
@anitagraham do you still need help with rebase?

**Comment by anitagraham** [comment]
Yes please, simi. Sorry I had to leave for a couple of days.

**Comment by simi** [comment]
@anitagraham I did quick rebase of your iconfont against master branch in https://github.com/refinery/refinerycms/tree/iconfont-by-anita. Can you please confirm it is ok?

After that I can squash commits and open proper PR.

**Comment by anitagraham** [comment]
Thanks @simi, that looks good.

**Comment by simi** [comment]
@parndt can I merge this manually?

**Comment by bricesanchez** [comment]
What are the last screenshots ?

**Comment by anitagraham** [comment]
Here are some screenshots:
page index
icon on hover

**Comment by parndt** [comment]
@simi sure

**Comment by simi** [comment]
continues in #2957

**Pull request closed without merging**
