### PR TITLE
Adding Arabic local files to Refinerycms

### PR DESCRIPTION
**Pull request by mabras**

### CODE REVIEW

**Comment by bricesanchez** [comment]
Hello @mabras ! 

Could you squash your commits into one ?

Thanks !

**Comment by bricesanchez** [comment]
@mabras is it ready to be merged ?

**Comment by mabras** [comment]
:+1:

**Comment by bricesanchez** [comment]
Awesome! Thank you!

**Comment by imidsac** [comment]
شكراً

**Pull request merged**
