### PR TITLE
Iconfont for real

### PR DESCRIPTION
**Pull request by simi**
closes #2920

### CODE REVIEW

**Comment by simi** [comment]
@anitagraham:

output_ebnhpj

**Comment by parndt** [comment]
I've got this alignment problem:

screen shot 2015-04-24 at 09 11 47

**Comment by parndt** [comment]
Problem when I run `rake assets:precompile`:

```
rake aborted!
Sass::SyntaxError: Undefined variable: "$icon_default_colour".
/code/parndt/refinerycms/core/app/assets/stylesheets/refinery/_icons.scss:17:in `icon'
/code/parndt/refinerycms/core/app/assets/stylesheets/refinery/_icons.scss:29
```

**Comment by sedrickcz** [comment]
Same issue as @parndt 
    rake aborted!
    Sass::SyntaxError: Undefined variable: "$icon_default_colour".
    /home/web/ruby/sedrick/sfouknemeto-stg/shared/bundle/ruby/2.1.0/bundler/gems/refinerycms-    17e6857fea26/core/app/assets/stylesheets/refinery/_icons.scss:17:in `icon'
    /home/web/ruby/sedrick/sfouknemeto-stg/shared/bundle/ruby/2.1.0/bundler/gems/refinerycms-17e6857fea26/core/app/assets/stylesheets/refinery/_icons.scss:29

**Comment by anitagraham** [comment]
Just testing variations of the fix. And I've tracked down the alignment problem.

**Comment by prokopsimek** [comment]
Sorry, but hover effects are really disgusting...

**Pull request merged**
