### PR TITLE
Generate authors in order to create a valid gemspec

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by parndt** [comment]
How are we supposed to know who the authors are?

**Comment by parndt** [comment]
Sorry, I get it now. At first I thought this was an issue not a PR.  What happens when author is not specified?

**Comment by bricesanchez** [comment]
I'm not able to bundle install the app

**Comment by parndt** [comment]
What I mean is if they don't pass it to the extension generator what is the output?

**Comment by parndt** [comment]
[Answered my own question](https://github.com/refinery/refinerycms/commit/7f127410c73d21bab1c76c54d3c4f38f68c927f7#commitcomment-16432282)

**Comment by ghoppe** [comment]
Aha! Happy that my stupid question answered yours. :)

**Comment by bricesanchez** [comment]
Soooooo ? XD

**Comment by parndt** [comment]
Tried it out, thanks!

**Comment by bricesanchez** [comment]
You're welcome :D

**Pull request merged**
