### PR TITLE
Html whitelist

### PR DESCRIPTION
**Pull request by bricesanchez**
This PR replaces #3154, it's just a rebase on master.

### CODE REVIEW

**Comment by anitagraham** [comment]
Thankyou for the rescue @bricesanchez

**Comment by bricesanchez** [comment]
You're welcome!

**Comment by bricesanchez** [comment]
@parndt, it's ready to be merged if you're ok.

**Comment by sintro** [comment]
Ok, and how I can remove some elements from whitelist? If I want to disable the possibility of including <script> in pages body?

**Comment by parndt** [comment]
`<script>` tags should already be disabled?

**Comment by anitagraham** [comment]
Well I suppose, if it were required we could include a blacklist if there was a demand (taking @parndt 's comment into consideration).

**Comment by sintro** [comment]
@parndt , I just tried to save ``<script>alert('hello')</script>;`` (by switching to HTML editor), and after that I successfully alerted when opened that page.
By reading this https://github.com/refinery/refinerycms/blob/c793da02180489f44f491804fe61ebfd7c127f58/pages/lib/refinery/pages/configuration.rb#L32 line I see, that there are only  Loofah::HTML5::WhiteList::ALLOWED_ELEMENTS whitelisted elements, which does not include 'script' tag, but probably it is rendered by ``=raw @page.content_for(:body)``, which I use in page\`s template.

**Comment by bricesanchez** [comment]
@sintro 

> Loofah::HTML5::WhiteList::ALLOWED_ELEMENTS whitelisted elements, which does not include 'script' 
Which is not explicitly allowed is forbidden.

> So I am sure it is rendered by =raw @page.content_for(:body)
The HTML sanitizer is for frontend only, so <script> tags could be recorded in backend but they will be sanitize in frontend.

**Comment by sintro** [comment]
@bricesanchez , exactly, that is what I have noticed in https://github.com/refinery/refinerycms/pull/3164#issuecomment-226680890, but the question is still here: what if I want to disable some of ALLOWED_ELEMENTS`s default tags?

**Comment by bricesanchez** [comment]
@sintro Ok, i understand. So you will have to override the `Refinery::Pages` configurable class if you want to disable more tags in frontend :

https://github.com/refinery/refinerycms/blob/c793da02180489f44f491804fe61ebfd7c127f58/pages/lib/refinery/pages/configuration.rb#L31-L33

**Comment by ttmthanh** [comment]
@bricesanchez How can I override it? I must create new modul and copy all about file configuration or something else? Please help me :'(

**Pull request merged**
