### PR TITLE
Spruced up the 'ol thing.

### PR DESCRIPTION
**Pull request by parndt**
Not ready yet..

Currently:

THE SPRUCE GOOSE?!?

This is loosely based on this UI design:

ui_15

# Help required:
Need to figure out a way to extend the white background to the bottom of the browser without showing a scroll bar or setting a background image on the body etc. Anyone know how that works best in 2015?

### CODE REVIEW

**Comment by parndt** [comment]
Apparently [height: 100vh](https://developer.mozilla.org/en/docs/Web/CSS/length) might be our friend - thanks @lengarvey

**Comment by roonie** [comment]
Setting the min-height to 100% can do the trick. For it to work, the parent has to have a height of 100%. Using a min-height has the pro of extending when the content grows.

**Comment by roonie** [comment]
Here is a quick preview how to do it
```html
  height: 100%
body
  height: 100%
  .thing_wrapper
    height: 100%
    padding: 52px 0 0
    box-sizing: padding-box
    .white_thing
      min-height: 100%
```

**Comment by parndt** [comment]
@roonie nice! Thank you for the example code! :heart:

**Comment by parndt** [comment]
Thanks, @roonie and @johanb for the push over the edge!

**Pull request merged**
