### PR TITLE
Set speakingurl-rails to 8.0.0, switch to poltergeist gem.

### PR DESCRIPTION
**Pull request by parndt**
Replaces #3080

### CODE REVIEW

**Comment by parndt** [comment]
@bricesanchez the sprockets error has disappeared, but now `getSlug` is undefined in the javascript.

**Comment by parndt** [comment]
@bricesanchez this error is because `speakingurl.js` is not found

**Comment by parndt** [comment]
I have to say this is quite a large dependency for such a small feature (used in one place, optionally)

**Comment by bricesanchez** [comment]
Yeah you're right, that's not good for us

**Comment by bricesanchez** [comment]
I think i've the fix https://travis-ci.org/refinery/refinerycms/builds/100263612
I've posted a new PR to speakingurl-rails : https://github.com/pid/speakingurl/pull/71
We should wait for his version bump

**Comment by parndt** [comment]
what about apps that aren't using sprockets? Must they now use it?

**Comment by bricesanchez** [comment]
I'm a little confused on what is the best way to fix this issue : 
We could just add the js directly in our assets directory ?

**Comment by bricesanchez** [comment]
I've merged this PR because it's fixing the sprocket-rails 3.0 blocker issue.

**Pull request merged**
