### PR TITLE
Fixed admin menu items duplicating after extensions code changing

### PR DESCRIPTION
**Pull request by sintro**
Fixing https://github.com/refinery/refinerycms/issues/3087#issuecomment-235118966 issue

### CODE REVIEW

**Comment by parndt** [comment]
This is great, I really like this code :wink:

Once this passes CI I'll merge it.

**Comment by sintro** [comment]
Nice, this method looks good to me also, because I think forcing the reloading or all the Refinery::Plugins after every Refinery::Plugin change is much less effective than just to filter an array one time.

**Comment by parndt** [comment]
Absolutely agree 😄

**Comment by parndt** [comment]
I've cherry picked this across to master too https://github.com/refinery/refinerycms/commit/23781a81db3e8ea4a16cfa06f36a15c4c4d2456c

**Pull request merged**
