### PR TITLE
Add icon to image picker warning

### PR DESCRIPTION
**Pull request by anitagraham**
Also change warning to clearer, more succinct  message

### CODE REVIEW

**Comment by anitagraham** [comment]
1. don't take shortcuts
2. always run tests locally

Some people live a life comptemplative or a life more ordinary. I am living a life more interrupted.

**Comment by bricesanchez** [comment]
@anitagraham Could you squash your commits ?

**Comment by anitagraham** [comment]
Will squash. when the moment arises.

**Comment by parndt** [comment]
Seems to fail CI

**Comment by parndt** [comment]
Seems like #3069 is failing for the same problem, though? Maybe there was a change to another library we use?

**Comment by bricesanchez** [comment]
Thanks @anitagraham !

**Pull request merged**
