### PR TITLE
Strong parameters in controller for generated refinery forms

### PR DESCRIPTION
**Pull request by ghoppe**

### CODE REVIEW

**Comment by parndt** [comment]
Any way we can have tests?

**Comment by anitagraham** [comment]
Moving this along..... is this the sort of test you want? (If @ghoppe agrees, I don't think I could push this into his PR anyway.) 

````ruby
# in /refinerycms/core/spec/lib/generators/refinery/form/form_generator_spec.rb, Line 23
    it "generates strong parameters for the form fields" do
      File.open("#{destination_root}/vendor/extensions/rspec_form_tests/app/controllers/refinery/rspec_form_tests/admin/rspec_form_tests_controller.rb") do |file|
        content = file.read
          expect(content.include?('@rspec_form_test = RspecFormTest.new(rspec_form_test_params)')).to be_truthy
          expect(content.include?('params.require(:rspec_form_test).permit(:title, :description, :choice, :another, :enable)')).to be_truthy
        end
      end
    end
````

**Comment by simi** [comment]
@anitagraham you can open PR against his fork and once it will be merged it will be part of this PR. But if you don't mind, I can finish this.

**Comment by anitagraham** [comment]
Go for it @simi

**Comment by simi** [comment]
Waiting for @anitagraham's confirm for https://github.com/refinery/refinerycms/compare/2936-tests.

**Comment by simi** [comment]
merged with test in https://github.com/refinery/refinerycms/commit/2e6bb6cd39be0c9bc833eba5a23491876a907b70 and https://github.com/refinery/refinerycms/commit/235af3c5de89fec989ea36b7795d364e188806d1

**Comment by bricesanchez** [comment]
:+1:

**Comment by ghoppe** [comment]
Thanks for specs!

**Pull request closed without merging**
