### PR TITLE
Merge cjbrew forms

### PR DESCRIPTION
**Pull request by parndt**
Replaces #2922

### CODE REVIEW

**Comment by parndt** [comment]
@simi what do you think about these changes, given your work on generators lately?

**Comment by simi** [comment]
Hello @parndt. Give me please day or two, since this is a huge change. It's honest to review this. :heart:

**Comment by stefanspicer** [comment]
I have not been following all the refinery issues and PR's as well as I'd like, but I'm really trying to stay in the loop more.  This is my first time looking at this on.  What, in a sentence, is this PR for?

I see:

* improved specs (if there were any there before?)
* includes_spam option

In #2999 I think I may have duplicated some of this work.  I've found the "moderation" (from the blog engine) feature covers the "spam" feature and more, so I integrated the blog moderation into the form generator.  I then found that every second time I generated a form I needed the objects to be displayed on the frontend of the site too (a testimonial, a comment, a story), so after doing this a few times I integrated the form generator into the engine generator.  I thought it made sense for them to be one.

Thoughts on this approach?

**Comment by parndt** [comment]
@stefanspicer Doesn't the engine generator already generate frontend? (index/show) whereas the form generator generates forms that get submitted on the frontend.
So, the engine generator handles the 99% of extensions which require no user input on the frontend except to look at things.

**Comment by parndt** [comment]
Either way you look at it, all of our generators generate far too much code and are too complicated to maintain.

**Comment by stefanspicer** [comment]
Yes, the engine generator generates frontend.  The problem I ran into was that I often needed a form (for a comment, testimony, story) that needed these features:

* [form] frontend form
* [form] "moderation" - reject / approve
* [form] notification email & setting for who to notify
* [engine] admin add/edit the comments
* [engine] frontend index view
* [engine] admin reorder (one case needed this)

I do realize that these are all fairly easy just to copy and paste in, but it just made sense to me that if these features are in any generator, then they should all be in the same generator.  That's why I merged the form and engine generator.  It is more complex, but I think it is less code to maintain overall.

I've never actually found that the generators generate too much code.  I do understand your pain in maintaining them!  .erb.erb in itself gets very messy.

**Comment by bricesanchez** [comment]
Could we milestone it to 3.0 ?

**Comment by bricesanchez** [comment]
:tada:

**Comment by bricesanchez** [comment]
@CJBrew Thank you for your awesome job on this PR !

**Pull request merged**
