### PR TITLE
Add doc standalone extension in your Rails Application

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by parndt** [comment]
@bricesanchez great stuff! I don't think we can merge it until that process actually works without errors.

**Comment by bricesanchez** [comment]
I will try take time to fix this process :)

**Comment by parndt** [comment]
also I think using `[ci skip]` means the required build pass step never finishes

**Comment by bricesanchez** [comment]
Should we avoid using `[ci skip]` or could you disable required CI when we use `[ci skip]` ?

**Comment by parndt** [comment]
I looked into it, but we can't get that granular.  I suppose, at that point, it'd be nice if Travis just reported success if `[ci skip]` were enabled.

**Pull request merged**
