### PR TITLE
Set new_page_parts to true in Dev

### PR DESCRIPTION
**Pull request by bricesanchez**
It saves time to set `new_page_parts` to true in Dev only.

### CODE REVIEW

**Comment by parndt** [comment]
Development mode should reflect production mode, so this creates a situation where a feature is expected to be available in production, because it's available in development mode, but then isn't. 

Doesn't this violate a principle of least surprise for our users?

**Comment by bricesanchez** [comment]
My users never creates page parts, for me it's a developper feature. 

But if your template needs custom page parts, it will be better to implement the feature "page parts by template" instead of letting the user guess what is the good page part for his template.

**Comment by bricesanchez** [comment]
i don't know what happens with this branch, i've rebased it and forced update, but i've made a mistake on  git, there is no merge on master.

**Comment by parndt** [comment]
I'm still :-1: on this

**Comment by parndt** [comment]
If the implementation were as you say, with templates specifying whether new page parts were allowed, then I'd support having this feature always enabled, without a config setting at all.

**Comment by anitagraham** [comment]
Sorry @bricesanchez , I'm with @parndt on this. No surprises in production

**Pull request closed without merging**
