### PR TITLE
Fixed scss deprecation warning

### PR DESCRIPTION
**Pull request by parndt**
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename core/app/assets/stylesheets/refinery/_mixins.css.scss to core/app/assets/stylesheets/refinery/_mixins.scss

### CODE REVIEW

**Comment by simi** [comment]
There's still a lot of P`.css.scss` files around.

*Be careful, sprocket's `require` doesn't work in `scss` AFAIK.*

**Comment by parndt** [comment]
So.. what should we do? Should we rename these files, or not? Or just rename them and stop using `require`?

**Comment by simi** [comment]
I think rename and using just `@import` should be solution here, but it needs to be tested first.

**Comment by parndt** [comment]
Fixed by #2892

**Pull request closed without merging**
