### PR TITLE
Remove deprecated heroku gem

### PR DESCRIPTION
**Pull request by bricesanchez**
```
Fetching: heroku-3.43.12.gem (100%)
 !    The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt.
 !    Download and install from: https://toolbelt.heroku.com
 !    For API access, see: https://github.com/heroku/heroku.rb
```

### CODE REVIEW

**Comment by parndt** [comment]
We need this to be present, it's [used in the generator](https://github.com/refinery/refinerycms/blob/f4b3cf3eb674cbdd5097f302f028262be41f6a70/core/lib/generators/refinery/cms/cms_generator.rb#L161-L183), and I'm pretty sure it's had that deprecation message for a long time now.

**Comment by bricesanchez** [comment]
It's provide by the toolbelt now and our guide explicit that we need to have the toolbelt.

**Comment by parndt** [comment]
My major complaint is that if people specify  --heroku it won't automatically set things up, it'll fail.  Maybe we should abort if the Heroku command isn't available?

**Comment by bricesanchez** [comment]
I've tried something, let me know if it's ok for you

**Comment by bricesanchez** [comment]
friendly ping @parndt

**Comment by bricesanchez** [comment]
🆙  😄

**Pull request merged**
