### PR TITLE
Rails 4.2 support

### PR DESCRIPTION
**Pull request by simi**
# TODO

- [x] use routing-filter gem instead of custom fork
- [x] check friendly id errors on [CI](https://travis-ci.org/refinery/refinerycms/jobs/50837759)

### CODE REVIEW

**Comment by simi** [comment]
The failing test is caused because this behavior:

on master:

```
Globalize.locale
=> :en
Refinery::Page.last.slug
=> "новости"
```

in this PR:

```
Globalize.locale
=> :en
Refinery::Page.last.slug
=> nil
```

**Comment by simi** [comment]
Do we need to wait for Globalize 5.1.0 here?

**Comment by simi** [comment]
Rails everywhere

giphy 3

**Comment by bricesanchez** [comment]
:confetti_ball: :tada:

**Pull request merged**
