### PR TITLE
New revised user experience - Refinery Glass

### PR DESCRIPTION
**Pull request by stefanspicer**
This replaces #2999.  It has been rebased and includes a few more features, fixes and refactored JS.

Here are a few highlights: https://youtu.be/8nZgeF-QwMo
Here is a demo site I set up.  Go and try it out: http://refineryglass.com

This PR works in conjunction with https://github.com/refinery/refinerycms-authentication-devise/pull/14

Development of Refinery Glass started in Oct 2014 and after over 1000 commits (that I've condensed into a few) we've launched this new refinery on 5 production websites.

## **Main** Features of Refinery Glass
* New look - main menu, sidebars, icons, contextual menu (#actions), responsive
* glass editor to replace wymeditor with grande.js integrated with refinery - edit content in place as it will show live
* Ajax is used for forms to enhance the user experience
* Invite admin - they activate and create a password.  A professional "Welcome to your CMS" experience.

## Still a lot left to do
* I've marked a bunch of tests as skipped, the reason shows my explanation.  This is a good place to start to get things up to speed
* The editor is very simple, doesn't have some of the features of wymeditor
* Multiple locales on pages needs to be re-integrated into the interface, and re-thought through
* I have a list that we need to prioritize, the above are the biggest things.

### CODE REVIEW

**Comment by bricesanchez** [comment]
That's a really could improvement. 

Should we start using it now and check if all extensions works well ?

**Comment by stefanspicer** [comment]
What do you mean @bricesanchez by "start using it now"?  We are using it in production, but that only means it works within the way we use refinery.

As to the extenstions, it is not a "check if they work well" but "port them over to the new html conventions" if that makes sense.  I recommend dropping support for Inquiries, and instead make sure the engine generator outputs a good inquiries engine.  I have a blog plugin started, it has some feature overlap with the current blog, but it also differs in many ways.  We can potentially come up with something in between.  I have never installed any other extensions, so I can't speak to them.

**Comment by bricesanchez** [comment]
By start using it now i mean in your opinion is it ready to be merged on master even if it remains works to do ?

I like your idea to drop the support of inquiries and improve the form generator.

**Comment by stefanspicer** [comment]
To be honest I don't know what it really means to have something merged into master.  Please note that there are a lot of skipped (essentially failing) tests.  I skipped them so that I could put a comment in and describe what is going on.  Some are just because I couldn't get the test to pass when I think it should.  With less automated tests it means we rely on more manual tests (which are all run withing our environment).

Back to the questions, I don't have a good idea who is running off of master, so it is really a question for them I guess.  We have dropped functionality with this update so I guess worst case scenario it is a scramble to re-build the missing functionality and fix the bugs that are still lurking.

**Comment by anitagraham** [comment]
Why dropping inquiries?

**Comment by anitagraham** [comment]
Looks good.

**Comment by parndt** [comment]
I like the idea of master branch always being working, _but unreleased and not necessarily supported_, software

**Comment by stefanspicer** [comment]
@anitagraham, my reasons for dropping support for inquiries:
* I found I always spent more time overriding things I needed to change (add a field, change the mailer, ...) than if all the code was right in front of me in vendor/extensions
* It is helping developers get into the "refinery way" faster to make the "inquiries extension" instead just be a list of commands like:
  * `rails g refinery:engine inquiry ...`
  * `rails g refinery:inquries`
  * `rake db:migrate`
  * `rake db:seed`
  * ...
* refinerycms-inquiries is just not far enough different from the generator to warrant a separate extension

**Comment by stefanspicer** [comment]
@parndt, I can confirm that this PR is working.  But I can see people potentially thinking it isn't "working" because of the missing features.  It adds features and removes some.  The main features removed at this point are:
* images library (this is intentionally removed)
* resources (I'll be adding a working version of this in very soon)
* page locales
* i18n - I'm pretty sure we've introduced a ton of hard coded English in the admin interface
* html editor - missing features, some intentional like an html view

**Comment by parndt** [comment]
@stefanspicer yeah, I think that's what I meant. Things like i18n are actually quite a big deal as we have users using many different languages

**Comment by stefanspicer** [comment]
Yes, I thought that would be a big deal. And the reason it was left out is simply that we have had no need (up to this point) for anything other than English, so it naturally sort of slips behind.

**Comment by JulianNacci** [comment]
Refinery Glass Authentication I18n will be finalized today, we will dig into Refinery I18n this week with a colleague.

**Comment by JulianNacci** [comment]
I18n will be a real challenge as we spoted hardcoded english in js, css (?!), views and controllers.

**Comment by stefanspicer** [comment]
@JulianNacci, yes, not a simple task.  I want to support you in any way needed.  If you want to put a list together of any tough ones, that might be helpful:
* Views - should be straightforward (just a lot of grunt work)
* Controllers - is this mainly error messages in json responses?  I wonder if json can be moved into a 'json' view or something to solve that.
* js - there's probably way more html in the js files than there should be.  I've moved a lot out into views, but this job probably just needs to completed.
* css - is it more than these 2 "content" lines: "New paragraph..." and "Move Here"?  We should move these into views and JS can store it in attach them as a data attribute to any element its needed (for css to pick up) - if you'd like us to handle this, I can make this change.

**Comment by bricesanchez** [comment]
@stefanspicer Don't hesitate to update your Pull Request, we will review it at soon we could find the time for it :)

**Comment by bricesanchez** [comment]
@stefanspicer Could you update your PR ?

**Comment by stefanspicer** [comment]
Thanks @bricesanchez, I'll do that soon.  We have an implementation for resources now, and we've updated the link editor among other things.  And I'll rebase to the latest. That is what you mean by "update" right?  Rebase it to the latest?

**Comment by bricesanchez** [comment]
@stefanspicer Yes please :)

**Comment by parndt** [comment]
Can some of these changes be made incrementally on top of the current product? i.e. can we avoid merging everything at once but build things up piece by piece until merging the UI changes are the natural thing to do?

Sorry, I know that's a frustrating thing to ask.

**Comment by stefanspicer** [comment]
Thank you @parndt, it's not that frustrating, and is something I've attempted to do already.  I actually have 9 other (fairly small) changes that I've extracted out of this in preparation to submit them each individually.

I've attempted to make each of the current 18 commits a separate "feature" of their own that follow the current tip of master.  The only exception is the first one `30134e8 New 'glass' interface for refinery`.   That is explained further in [my comment from back in June](https://github.com/refinery/refinerycms/pull/2999#issuecomment-117445590).  Instead of reviewing the code directly, it may be helpful to review my comment.  Instead of me going and attempting to break that one apart, I've put the time into breaking it apart in theory (in that comment).  If we can work together to come up with a plan, I can put the time into breaking it into the PRs that make sense.

**Comment by stefanspicer** [comment]
@parndt shall we work on a plan together for how this should be broken out?  Or @bricesanchez as you dig into this PR maybe you'll have some more insight and can speak to this?

**Comment by parndt** [comment]
I am supremely low on time right now, sorry.  Feel free to ask me directed questions though and I'll do my best!

**Comment by bricesanchez** [comment]
@stefanspicer I've dig into this PR and i'm sure the result of your work could be the future of Refinery CMS.

I'm in favor of splitting this PR to be able to make a good review and reduce the number of regressions or bugs.

In the other way, i'm interested to try it as it on a new project and see what happens.

I've also seen that there is nearly no changes in controllers or models, only views, css and JS and i'm asking myself if we could use it as an engine before merging it.

If we split the PR, we could make this plan : 

1. @stefanspicer : Provide a PR to change layout of the admin (sidebar with plugin menu and general CSS)
@refinery/collaborators :  Be sure that all specs are running and all legacy views (pages, resources, images) works. 
2. @stefanspicer : Provide a PR to change the admin views
@refinery/collaborators  Be sure that all specs are running and all legacy views (resources, images) works.

3. @stefanspicer : Provide a PR to add live editor feature
@refinery/collaborators :  Be sure that all specs are running and all legacy views (resources, images) works.

**Comment by stefanspicer** [comment]
I think your first comment about the future of refinery is actually my biggest question.  Before I go and put even more hours into this, I need to see some people to agree that this is the future of refinery.  My team and I see how refinery could become the best CMS for developers to very efficiently provide a custom solution while surprising and wow'ing their client at the same time.

If you are willing, I think the 2-4 hours you spend trying this out on a new project will give you more insight than the 12-24 hours I could put in splitting this out.  I would even gladly work with you on getting it set up and walking through some things as documentation is currently lacking.

This can definitely be an engine, but I don't think this is the way to go.  My pain in that was that it started out as an engine and was one up until Apr 2015 when I put the effort in to clean it up and bring it into the refinery core while being careful not to revert all the changes that happened while we were off in our own fork.

So if you're okay with it, I'll wait until you have at least attempted to use this on a project and we'll probably come out of that with a more specific (and hopefully better) plan on how to merge this PR.  Let me know if/when you want me to jump in and help out on your project.

**Comment by bricesanchez** [comment]
I've tried your PR on an existing project in version 3.0.2 and on a dummy project.

This is my thoughts : 

_Pros_ : 
- The new look and feel is nice!
- The live editor is a very interesting feature.

_Cons_ : 
- This PR is too big to be reviewed and merged. The review process is really important because after the merge Refinery contributors will endorse your work and they will have to deal with the issues and the maintenance. So they have to be confortable with your work before to merge it. Split this PR into incrementable PRs is a good start in order to move forward and to be reviewed.
- There is no support of legacy CSS but my PR could help you soon https://github.com/refinery/refinerycms/pull/3165 to load legacy CSS.
- a current project can't be easily updated without breaking a lot of UI.

Questions : 
- Why don't you use turbolinks ?

**Comment by parndt** [comment]
> Why don't you use turbolinks ?

We don't either :wink:

**Comment by bricesanchez** [comment]
@parndt We don't because we haven't rebase, fix and merge this PR : https://github.com/refinery/refinerycms/pull/2732 :D

**Comment by stefanspicer** [comment]
I'm glad you like the look.  It's had many iterations.  This live editor idea is the future of the web and refinery has an opportunity here to lead on certain aspects if we want to take this on.  Quick note about turbolinks: We're planning on going that way, just trying to keep changes as small as possible and modifying the `request.xhr?` checks seemed like too much at this point.

Updating a project to this version is going to be somewhat painful regardless of how we slice it.  I think creating good guides will help with this.  For example, you have a legacy FAQ engine.  Regenerating it with the same parameters and then using `git add -p` to add only the admin views is pretty simple to gets you a long way.  Then you just need to re-add any admin interface features.  But I agree with you, upgrading is not simple.  The question is, are we going to make it worthwhile for people to upgrade and do that work?  I think if we sell it right, people will be all over it.  But that's my opinion.

On to splitting and merging incrementally.  Let's go one chunk at a time building upon the current 3.0.2.  What is the first PR chunk now that you've dug in a bit?  Same as before @bricesanchez "change layout of the admin (sidebar with plugin menu and general CSS)"

Outcome of this:
refinery-pr1

**Comment by stefanspicer** [comment]
Is that the plan @bricesanchez? It may make more sense to take the menu and index views as the first chunk.

**Comment by parndt** [comment]
Seems like it's using the old icons? Otherwise looks generally good.

**Comment by bricesanchez** [comment]
Yes @stefanspicer :)

**Comment by bricesanchez** [comment]
@stefanspicer You're welcome! 

`admin/users/index` should be a feature for `refinerycms-authentication-devise` because there is no `User` concept in the core of the project.

We should stay concentrate on this repo before extensions repos.

We could work on the layout/views CSS styles for backend (pages, images, resources).

No need to work on the inline editing feature at this time.

What do you think?

**Comment by stefanspicer** [comment]
I'd prefer to do the admin/users/index view next just because it is most of the way there already.  But I'm OK to switch gears.  Even though refinerycms-authentication-devise has been technically broken out into an extension, I still see it as very much apart of the core.

So my fist choice is admin/users/index.  Second choice is to do admin/resources/index next.  I want to do a simpler index first, then move to admin/pages/index.  Let me know, and I'll get to work.

**Comment by bricesanchez** [comment]
@stefanspicer I'm ok with that, i will help you to get these PRs merged :)

**Comment by parndt** [comment]
Yes, users are still sort of part of the core, but not the devise implementation.. will be interested to see what you come up with anyway.

**Pull request closed without merging**
