### PR TITLE
Adding byebug_history to .gitignore

### PR DESCRIPTION
**Pull request by sturad**
Adding debugger session log to .gitignore.  Seems beneficial and harmless.

### CODE REVIEW

**Comment by parndt** [comment]
You may find it useful to know that you can have a user global `.gitignore` file at `~/.gitignore` or similar.

[Here are some instructions from GitHub](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)

**Comment by sturad** [comment]
Thanks for the info on global .gitignore.

**Comment by simi** [comment]
@parndt merged? byebug is not (prod/dev) dependency of Refinery CMS.

**Comment by parndt** [comment]
¯\_(ツ)_/¯ it doesn't hurt

**Pull request merged**
