### PR TITLE
Remove skip_pipeline option for visual_editor_stylesheets and custom_…

### PR DESCRIPTION
**Pull request by bricesanchez**
…stylesheets

This should fix https://github.com/parndt/refinerycms-wymeditor/issues/47

But how to fix the spec @parndt ?

### CODE REVIEW

**Comment by parndt** [comment]
@bricesanchez 6601ba12cc5befbfc525e2f3122cd02e357d023b ?

**Comment by bricesanchez** [comment]
I'm not sure to understand your comment

6601ba1 was good to fix the spec but 6601ba1 fix the issue parndt/refinerycms-wymeditor#47 .

🤣

**Comment by parndt** [comment]
What I mean is you introduced the `skip_pipeline` thing to fix an issue, just making sure it won't undo that fix 😄

**Comment by bricesanchez** [comment]
@parndt i've updated the PR, could you review it?

@xnagpa i confirm the fix and you?

**Comment by bricesanchez** [comment]
🆙 🙃

**Pull request merged**
