### PR TITLE
Left side tabs

### PR DESCRIPTION
**Pull request by bricesanchez**
Finish this feature, thanks all!

### CODE REVIEW

**Comment by bricesanchez** [comment]
@robyurkowski @simi @parndt 
I change the colors of the tabs after discussions. 
Could we merge it like that and improve the admin in different time?

**Comment by simi** [comment]
Can you rebase please @bricesanchez ?

**Comment by simi** [comment]
@parndt is this ok for 3.0?

**Comment by parndt** [comment]
Please rebase as a number of these commits are already in master.

**Comment by parndt** [comment]
For any design changes can you please include before and after screenshots?? 😍

**Comment by bricesanchez** [comment]
Of course, the screenshot was on Gitter : 
Screenshot of left side tabs news colors

**Comment by simi** [comment]
@bricesanchez can you provie both (before/after) screenshots please?

*also that rebase would be handy*

**Comment by bricesanchez** [comment]
@simi i rebase my branch, it should works now. I added before and after screenshot. I made colors changes after your comments. But at this time i'm with the already merged feature ;)

**Comment by simi** [comment]
Hmm, it can't be merged automatically. That's not problem if you're having troubles with this. But I think this should wait for almighty @parndt.

**Comment by bricesanchez** [comment]
Almighty @parndt, @robyurkowski  prefers the before and me too. So i close the PR

**Pull request closed without merging**
