### PR TITLE
Add Rails::Html::PermitScrubber in section_presenter

### PR DESCRIPTION
**Pull request by bricesanchez**
This allow data-attributes in HTML

### CODE REVIEW

**Comment by anitagraham** [comment]
How does this interact with the `Refinery::Wymeditor.whitelist_tags`?

**Comment by bricesanchez** [comment]
@anitagraham it does not interact because `Refinery::Wymeditor` is not mandatory on Refinery.

**Comment by anitagraham** [comment]
Refinery::Wymeditor may not be mandatory, but that doesn't mean that there will be no interaction.

Whatever method I use to input HTML, if I use a tag not included by `Loofah:::HTML5::Whitelist::ALLOWED_ELEMENTS` who wins?
As Loofah is called at the rendering of the content it would appear that Loofah wins. 

So

* It may exclude elements which the user has whitelisted in Refinery::Wymeditor (or has added in some other way)
* the description of the PR should read "Limit elements to those permitted by Loofah:::HTML5::Whitelist::ALLOWED_ELEMENTS"
* Refinerycms-wymeditor should also note (somewhere) that the configuration is subject to the elements allowed by Loofah.
* Is there value in having a configuration, which, combined with the standard Loofah list will permit a site to use other elements or attributes?

I assume that the list of allowed_elements is fairly comprehensive so that - in general - there won't be a problem.

However, wymeditor has been the default editor for Refinery until now, so changes which will impact on commom usage should be noted.

*Note* I have passed information on using the `Wymeditor::whitelist_tags` to an inquirer on Gitter or Google Groups quite recently, so this is not necessarily an old or obsolete usage.

**Comment by bricesanchez** [comment]
@anitagraham 

You're right, `Refinery::Wymeditor` should be updated to interact with `Loofah` or display a note because actually `Loofah` wins in all cases. 

This current PR fix this merged PR https://github.com/refinery/refinerycms/pull/3117 because data-attributes was not allowed.

**Comment by parndt** [comment]
Great, this was causing major grief will trying to use recaptcha!

**Comment by anitagraham** [comment]
https://github.com/flavorjones/loofah/issues/69 The source tag used inside the the `video` and `audio` tags is not supported by the Loofah Whitelist.
I am working on bringing `refinerycms-videojs` up to Refinery 3 compatibility and my source tags are being gutted. Not sure yet whether what I am seeing when editing the page is Loofah or Wymeditor, but it *will* be an issue when it comes to viewing the page.

**Pull request merged**
