### PR TITLE
Restyled big orange site bar buttons to remove orange.

### PR DESCRIPTION
**Pull request by parndt**
Seems to be where things are heading

Before:
screen shot 2015-03-21 at 16 51 39

After:
screen shot 2015-03-21 at 16 50 11

### CODE REVIEW

**Comment by simi** [comment]
:+1:

**Comment by parndt** [comment]
We should also consider a different font

**Comment by anitagraham** [comment]
Font: for the whole system or just the site bar buttons?
To do?
better mobile readability?
distinguish active item from descriptive text?

**Comment by parndt** [comment]
Whole system, dunno, just an offhand comment

**Comment by anitagraham** [comment]
aaah... for fun!

**Pull request merged**
