### PR TITLE
Fixing SQL Server Order By Error

### LINKED ISSUE #2980: Pages admin throws ActiveRecord::StatementInvalid when using SQL Server
Seems to be caused by the 'lft' column being included in the order by twice.  Sql Server doesn't like this.  I can fix it by just removing [this line of code](https://github.com/refinery/refinerycms/blob/master/pages/app/controllers/refinery/admin/pages_controller.rb#L7)  Is that sort necessary here?

```
ActionView::Template::Error (TinyTds::Error: A column has been specified more than once in the 
order by list. Columns in the order by list must be unique.: EXEC sp_executesql N'SELECT [refin
ery_pages].* FROM [refinery_pages] WHERE [refinery_pages].[parent_id] IS NULL ORDER BY lft ASC,
 [refinery_pages].[lft] ASC'):
    1: <ul id='sortable_list'>
    2:   <%= render :partial => 'page', :collection => @pages.roots  %>
    3: </ul>
    4: <%= render '/refinery/admin/sortable_list', :continue_reordering => !!local_assigns[:con
tinue_reordering] %>
```

### PR DESCRIPTION
**Pull request by BrandonJoyce356**
WIP - Need to determine if this breaks anything else, and maybe write a regression test if possible.  
Resolves #2980

### CODE REVIEW

**Comment by parndt** [comment]
All tests seem to pass, though I'm not sure if there are any that check that it's ordered properly.

**Comment by BrandonJoyce356** [comment]
I could add one if you want.  Maybe an additional test here that uses the reorder function and then refreshes the page?  https://github.com/refinery/refinerycms/blob/master/pages/spec/features/refinery/admin/pages_spec.rb#L52

**Comment by parndt** [comment]
That sounds very lovely thank you

**Comment by BrandonJoyce356** [comment]
Simulating the drag-n-drop is proving to be quite difficult.  I even tried [this](https://github.com/mattheworiordan/jquery.simulate.drag-sortable.js), but it seems to not work consistently.  Any tricks up your sleeve, or should I just resort to some sort of API call to do the reorder rather than trying to simulate browser interactions?

**Comment by parndt** [comment]
I think calling `update_positions` is best.. but if that's also too troublesome then I don't want to waste your time and we can probably avoid the tests.. we've gotten this far without them! However, tests are the preferred.

**Comment by BrandonJoyce356** [comment]
Let me explore that route for a bit unless you're in a hurry to merge this.  I could work on the tests on a separate PR too.

**Comment by BrandonJoyce356** [comment]
Sorry for the delay on this.  I'll have some more time on it this weekend.

**Comment by parndt** [comment]
@BrandonJoyce356 thanks!

**Comment by BrandonJoyce356** [comment]
This fails when running tests with postgresql or mysql for some reason.  Looking into it.

**Comment by BrandonJoyce356** [comment]
Ah, sqlite starts with index 1, pg starts with 0.  Pretty sure that's it.  I'll find a way to avoid the index numbers.

**Comment by BrandonJoyce356** [comment]
Yay, tests pass.  Ready for review @parndt

**Comment by parndt** [comment]
Works for me!

**Comment by parndt** [comment]
Thanks!

**Pull request merged**
