### PR TITLE
Fix cms generator with heroku arg

### PR DESCRIPTION
**Pull request by bricesanchez**
This should fix `heroku` arg on cms generator

### CODE REVIEW

**Comment by bricesanchez** [comment]
It looks like the error is still there or the generator build the new app with the rubygems source instead the github source: 

```
rails new my_new_application -m https://raw.githubusercontent.com/refinery/refinerycms/69572e9f31b967c78d2c444550984f7ccdc25c80/templates/refinery/installer.rb --heroku
```

**Comment by parndt** [comment]
>[!] There was an error parsing `Gemfile`: syntax error, unexpected end-of-input, expecting keyword_end. Bundler cannot continue.

**Comment by bricesanchez** [comment]
Yes, the last ´end´ does not print in the Gemfile, i don't understand why, could you help me to figure out?

**Comment by parndt** [comment]
I am debugging it locally.

**Comment by bricesanchez** [comment]
Thanks!

**Comment by parndt** [comment]
I think it might have been a mistake adding `--heroku` into the test, because we don't want to be contacting third parties (especially when they'll set up a hosting account for us!) in automated testing.  See this build job for what I mean: https://travis-ci.org/refinery/refinerycms/jobs/145453641

**Comment by bricesanchez** [comment]
Oh yes! We don't want this. And i think we don't want to automatically push to heroku even if it's not on test env.

**Comment by parndt** [comment]
Well that's the way it's always worked for years now so I think that part is okay. It's just the testing of it that's not.

**Comment by bricesanchez** [comment]
It's like an hotfix for me, if we remove --heroku, we don't know if the heroku script works. We don't want to push with no prompt message or conditional check. So it could be part of the 'heroku Q&A' i have to do!?

**Comment by parndt** [comment]
Well then we need an additional argument like `--no-deploy` which overrides that part of the Heroku process?

**Pull request merged**
