### PR TITLE
Update 3.0.6 release date in changelog.

### PR DESCRIPTION
**Pull request by simi**
Alternative approach can be releasing of 3.0.6 without latest 4.0 changes.

### CODE REVIEW

**Comment by parndt** [comment]
Yeah, I'll release 3.0.6 and then we can update this PR with the release date.

**Comment by simi** [comment]
:eyes:

**Comment by parndt** [comment]
@simi released 😄 https://rubygems.org/gems/refinerycms/versions/3.0.6

**Comment by simi** [comment]
Should be backported to 3-0-stable also IMHO. Should I open different PR?

**Comment by parndt** [comment]
@simi yes please! 😄

**Comment by simi** [comment]
ahh, it is there already - https://github.com/refinery/refinerycms/commit/7d00a47e2f83950073f256e9f9b2c3be345a429d

**Comment by parndt** [comment]
Oh yeah 😅

**Pull request merged**
