### PR TITLE
Google Analytics only if Rails.env.production?

### PR DESCRIPTION
**Pull request by prokopsimek**
What about this one? Most of time we don't want to track on other environment than production...

### CODE REVIEW

**Comment by parndt** [comment]
It currently only works if the page code is set and if it's not a local_request? (which it usually is in development mode) and you're not logged in.  This code is in the partial itself.

Is this not working?

**Comment by prokopsimek** [comment]
@parndt It is, but if you want to use more than only development & production environment... E.g. "staging" or "beta"?

**Comment by parndt** [comment]
In this case perhaps it would be better to set the analytics code via ENV and neglect to set it in the staging environment?

**Comment by prokopsimek** [comment]
ok

**Pull request closed without merging**
