### PR TITLE
Add protect_from_forgery with: :exception

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by simi** [comment]
Are you sure this will fix it? No specs?

**Comment by bricesanchez** [comment]
i don't know how to test it and i asking myself why we added this line in core/lib/refinery/application_controller.rb but it fix the CSRF discovered by @cor3sm4sh3r.

**Comment by simi** [comment]
I saw that. But this just raise exception instead of using blank session when CSRF is detected. Am I right? I'm not sure how it can solve this problem.

**Comment by simi** [comment]
Si am I not right?

**Comment by parndt** [comment]
@simi I thought that it was better to raise an exception to prevent the possibility of anything being created/used incorrectly by the system.

**Comment by simi** [comment]
You're out of scope of creating or using things since you have empty session for that request.

**Comment by simi** [comment]
I'm not against this patch, but I don't think it is fixing any issue.

**Comment by parndt** [comment]
Fair point.  At least by handling this with an exception it gives developers an opportunity to rescue this exception and do something else?

**Comment by cor3sm4sh3r** [comment]
hi all,
Raising the exception fixed csrf issue but i think this should be more
likely solution.

rescue_from ActionController::InvalidAuthenticityToken do |exception|
  sign_out_user # Example method that will destroy the user cookies
end

On Fri, Feb 12, 2016 at 3:26 AM, Philip Arndt <notifications@github.com>
wrote:

> Fair point. At least by handling this with an exception it gives
> developers an opportunity to rescue this exception and do something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/refinery/refinerycms/pull/3101#issuecomment-183075143>
> .
>



-- 
shravan kumar budharap
cor3sm4sh3r

**Comment by parndt** [comment]
@simi @bricesanchez  ^ I think that suggested code is better too, what do you think?

**Comment by bricesanchez** [comment]
:+1:

**Comment by simi** [comment]
http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-protect_from_forgery `:reset_session` option is there. But as I stated multiple times here, I don't see a reason how this can fix some issue.

The only difference is with this exception is raised, without this empty session is provided for given request (future valid requests can use this session again). There's third option (:reset_session) to destroy session at all (no future valid request can continue in this session).

But in no case you should be able to access session when CSRF protection is activated.

Or am still I missing something?

**Comment by bricesanchez** [comment]
I thinking about creating a spec to check this issue. So after that qe will see if it really works for us but i agree with @simi there is probably something inside this bug we doesn't discover yet...

**Pull request merged**
