### PR TITLE
Fix overriding hierarchy

### PR DESCRIPTION
**Pull request by prokopsimek**
Because of: https://github.com/refinery/refinerycms/issues/2899

### CODE REVIEW

**Comment by simi** [comment]
Not a good idea at all. But we can change plugin registering to prepend new ones.

**Comment by prokopsimek** [comment]
@parndt ?

**Comment by parndt** [comment]
We should instead change the plugin registration code to `.unshift` rather than `<<` when registering a new plugin.

**Comment by parndt** [comment]
Closed by #2992

**Pull request closed without merging**
