### PR TITLE
Add refinerycms-i18n to gemfile template for engines

### PR DESCRIPTION
**Pull request by CJBrew**
To fix issue https://github.com/refinery/refinerycms/issues/2835

This adds the dependency to an engine's Gemfile.

Manually tested with a dummy app.

### CODE REVIEW

**Comment by simi** [comment]
@parndt should be this locked to stable release once new stable release will be out?

Also @CJBrew can you use new has syntax?

**Comment by CJBrew** [comment]
Tweaked the hash syntax.  Thanks.

**Comment by parndt** [comment]
@simi yes absolutely, though currently it breaks out of the box so this seems good.  @CJBrew Do we need this for forms as well?

**Comment by CJBrew** [comment]
@parndt  yes, I think it'll be needed on Forms. 

But I've not attempted to merge the work I did on forms generator up to Edge, so there's currently not even a Gemfile to add it to.

**Comment by parndt** [comment]
No longer required because of #2846

**Pull request closed without merging**
