### PR TITLE
Update refinerycms-dragonfly gemspec for release.

### LINKED ISSUE #3370: refinerycms-images references refinerycms-dragonfly which doesn't exist
https://github.com/refinery/refinerycms/blob/4.0.2/images/refinerycms-images.gemspec#L22

https://rubygems.org/search?query=refinerycms-dragonfly

```
source 'https://rubygems.org'

ruby File.read('.ruby-version').chomp

gem 'rails', '~> 5.1.6'

gem 'pg'
gem 'puma'
gem 'refinerycms', '4.0.2'
gem 'i18n', '0.9.5'
gem 'sass-rails'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
```

```
$ bundle
...etc...
Fetching refinerycms-images 4.0.2
Downloading refinerycms-images-4.0.2 revealed dependencies not in the API or the lockfile (refinerycms-dragonfly (~> 1.0)).
Either installing with `--full-index` or running `bundle update refinerycms-images` should fix the problem.

In Gemfile:
  refinerycms was resolved to 4.0.2, which depends on
    refinerycms-images
```

### PR DESCRIPTION
**Pull request by parndt**
Fixes #3370

### CODE REVIEW

**Comment by parndt** [comment]
@anitagraham is the dependency on core correct?

**Comment by anitagraham** [comment]
It may need it for the engine which references `Refinery::Engine, Refinery::Plugin and Refinery.register_plugin`.

**Comment by parndt** [comment]
@anitagraham I tried to make you an owner of the gem but rubygems.org doesn't recognise your email address.

**Comment by anitagraham** [comment]
I've now signed up to rubygems as anita@joli.com.au (anitagraham). And thanks.

**Comment by parndt** [comment]
Done!

**Pull request merged**
