### PR TITLE
Features/edit this page fixes issue #2800

### PR DESCRIPTION
**Pull request by darmens**
Provides an "Edit this page" link in the site bar, fixes issue #2800

### CODE REVIEW

**Comment by darmens** [comment]
@simi What, this?

screenshot 2015-01-02 11 32 47

**Comment by simi** [comment]
Can you squash commits @darmens ?

**Comment by darmens** [comment]
sure!

**Comment by ugisozols** [comment]
:+1:

**Comment by simi** [comment]
:clap:

**Pull request merged**
