### PR TITLE
Activate full-page-cache on production

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by parndt** [comment]
Are we saying that this will work in _every single production environment_?

**Comment by bricesanchez** [comment]
It will work on production mode, i assume we does not need cache in dev mode.

**Comment by parndt** [comment]
I'm :-1: on this.  It forces people to have a new dependency on `actionpack-page_caching` which they don't currently need.

**Comment by bricesanchez** [comment]
Me too finally, i've forgot the dependency.

**Pull request closed without merging**
