### PR TITLE
Use custom capture implementation in tests.

### PR DESCRIPTION
**Pull request by simi**
reference: https://github.com/rails/rails/pull/13392#issuecomment-62839760

It removes deprecation warnings.

### CODE REVIEW

**Comment by simi** [comment]
ping @parndt

**Comment by simi** [comment]
output_l9txun

**Comment by simi** [comment]
output_ebnhpj

**Comment by papricek** [comment]
:heart:

**Comment by parndt** [comment]
Okay so how do I claim my free iPad?

**Pull request merged**
