### PR TITLE
New revised user experience - Glass

### PR DESCRIPTION
**Pull request by stefanspicer**
On behalf of my entire team at Glass Canvas, I'm submitting this Pull Request.  It is a start towards moving Refinery to the next level.  Refinery is a great code base and an amazing CMS, and we'd like to see it make splash in the world of CMSs!  Who's with us?  At Glass Canvas, we work solely with non-profit and social efforts to give them the best, and refinery is the best!

Development of 'glass' (its code name that you'll see all over the code) started in Oct 2014 and after almost 1000 commits (that I've condensed into a few) we've launched this new refinery on 4 production websites.  This addresses much of what is discussed in issues #2731 #2934 #2833 and others.  I just spent a few days and integrated this with master, as it was based off of 2.1.5.  Our production websites are still running 2.1.5.

## **Main** Features of Refinery Glass
* New look - main menu, sidebars, icons, contextual menu (#actions), responsive
* glass editor to replace wymeditor with grande.js integrated with refinery - edit content in place as it will show live
* Ajax is used for forms to enhance the user experience
* Creating a new admin sends an invite email so they can activate their account and pick a password.  This makes for a more professional "Welcome to your CMS" experience than telling them their username and password.
 
Here is a quick demo I created for @parndt a few months ago. http://youtu.be/Gh1l_Yh8Mvo  Download and give it a spin, I'm sure people will have questions and comments.

## Still a lot left to do
* I've marked a bunch of tests as skipped, the reason shows my explanation.  This is a good place to start to get things up to speed
* The editor is very simple, doesn't have some of the features of wymeditor
* Multiple locales on pages needs to be re-integrated into the interface, and re-thought through
* I have a list that we need to prioritize, the above are the biggest things.

### CODE REVIEW

**Comment by stefanspicer** [comment]
# Config for Inviting a User
For those trying out the invite a user, you will need email configured and a devise config file with at least this:
```
Devise.setup do |config|
  # ==> Mailer Configuration
  # Configure the e-mail address which will be shown in Devise::Mailer,
  # note that it will be overwritten if you use your own mailer class
  # with default "from" parameter.
  config.mailer_sender = '"no-reply" <no-reply@localhost>'

  # Configure the class responsible to send e-mails.
  config.mailer = 'Devise::GlassMailer'
end
```

For production, you also need to allow enough time for users to receive the invite email and activate their account:
```
config.reset_password_within = 7.days
```

**Comment by anitagraham** [comment]
I like the inline editing. How adaptable is it for people with vision/mouse control problems?
Is there a demo site?

**Comment by stefanspicer** [comment]
I have no experience adapting a web app for the visually impaired.  I've never been asked about that.  So to date this has not been looked at, and I don't know how difficult that would be to do.  We have done some basic tested for keyboard control, so tabbing between fields works for the most part.

No demo site yet.  It wouldn't be too hard for me to setup.  I have yet to setup a site on refinery 3, this pull request is the result of my first time looking at refinery 3.

**Comment by simi** [comment]
@stefanspicer this looks huge. I can review this and help you to make test passing, but unfortunately I'm out of country until Tuesday.

Can you post some screens here please?

**Comment by stefanspicer** [comment]
@simi, I think the screencast shows it better, but here are some screenshots for you.

glass-page-index
glass-grande2
glass-sidebar-menus
glass-add-admin

**Comment by simi** [comment]
@stefanspicer amazing. Thanks for screens and sorry I totally missed video link.

**Comment by gogogarrett** [comment]
Looks great. Well done. Even MORE well done, for pushing this back upstream. :+1:

**Comment by anitagraham** [comment]
I wasn't thinking specifically of the seriously visually impaired. Just for the slightly aged, or for those whose mouse control isn't really fine, whether due to age, neurological problems (parkinsons, ms etc) or poor motor control. Good to hear that keyboard control is there.

**Comment by whosdustin** [comment]
I want!  How can I help / get a hold of this?

**Comment by stefanspicer** [comment]
Hi @whosdustin, I'd be so happy to have you try it out.  You should be able to use it with:
```
gem 'refinerycms', :git => 'https://github.com/stefanspicer/refinerycms.git', :branch => 'glass'
```
There are probably some things you'll run into and have questions about as soon as you start using the engine generator and adding your own CSS & JS for your site. I need to build up some documentation.

If you need it a little more stable, you can use the 'glass-stable' branch for now.  I'll be using that branch for some production sites of ours here soon.

Please ask questions as they come up.

**Comment by bricesanchez** [comment]
Wow amazing !

**Comment by parndt** [comment]
How straightforward would it be to extract the editing concerns into an extension, like [what happened with refinerycms-wymeditor](#2567)? I just don't want to see us getting locked in to another editor again. :smile:

**Comment by stefanspicer** [comment]
@parndt that totally depends how much you extract.  I see 2 fairly clear lines:
1. Extract just the editing of an html block (so basically a page part, or a single text column from the database)
2. Extract, essentially, the edit view of a page

The former approach would be fairly simple to extract and drop in wymeditor or tinyMCE.  The latter would be more involved.  Refinery has undergone a lot of changes to allow for the show view to be displayed within the edit view (with all assets), and the form is in the sidebar with hidden fields.  Refinery would then need to keep those complexities (that are required for the Glass Editor, with grande.js), but simply not make use of it for certain editors.

I think it would be best to first come up with a plan of how another editor would fit in, figure out what is the user experience would be, and then the line of what to extract would become more clear.

**Comment by anitagraham** [comment]
@stefanspicer  option 1 seems far more likely, as not all page parts are edited using the visual editor.

I'm finding it hard to comment on glass because it is such a large set of changes, and there are so many questions.

**Comment by anitagraham** [comment]
Question 1:  js/css. What frameworks are you using? I can see jquery-ui being called, and sass-bootstrap and your own icon-font. Are there other asset packages I haven't noticed? 

Background: Refinery 3 will go out with font-awesome icons. It was planned to try moving to zurb-foundation as a framework - using bootstrap would be much the same I think.

Q2. We/I had moved away from sprockets manifest files to using SASS partials. Any thoughts on pros/cons for each of those? 

I have been working on using foundation components to replace jquery-ui and home-grown components in Refinery (as part of the move to foundation).  The big ones I can see are dialog windows and sortable lists. What have you done/thinking of/planning for in this area?

I like your interface, and would like to continue working on the refinery backend's frontend, but I would like to know more before I dive in!   

Anita

**Comment by stefanspicer** [comment]
@anitagraham ,

Q1: We currently use bootstrap and a few components from semantic UI (http://semantic-ui.com/). I've attached a 2 screenshots of semantic-ui modals that we've integrated.  We plan on continuing with bootstrap and are quite excited about the changes coming soon in bootstrap V4. Foundation seems fairly on par with bootstrap right now so we plan to continue using bootstrap as it is already integrated into the refinery interface and is only going to get better.

As far as the icons go, if you want us to integrate fontawesome we can do that while also keeping our pared down custom icon font.

Q2: I remember reading about how SASS imports are better than using sprockets, but I don't remember all the reasoning.  So most of it uses SASS imports, but I just realized that the highest level includes use sprockets, so I'll switch that over to make it consistent.

semantic-ui-modal1
semantic-ui-modal2

**Comment by stefanspicer** [comment]
Oh, and I just remembered.  Looking to the future a bit, we are getting into react and really liking it, so we may eventually be using react on index pages (only where it makes sense).  One use case would be to make a page into a redirect right from the index page (fill in the 'link_url' attribute).  I'm thinking we'll have a json interface in crudify (hopefully minimal changes) to easily allow for react components to do all the crud stuff from within generated engines.

**Comment by parndt** [comment]
It'd be great to make improvements as incrementally as possible, large pull requests will tend to gather dust!

**Comment by anitagraham** [comment]
One more Q: AMD/modular js
Does this have a place within Refinery?

**Comment by stefanspicer** [comment]
Hi @parndt 

If attempting to sit down for a few hours to do a code review of this, then yes, this is a monster.  I have done quite a bit of work splitting it up to make it incremental, but with some direction we can split it up more.  I initially broke it out into about 8 or 9 branches, but with a number of them all depending on each other it made more sense to put them in one branch.  It left 4 other small independent features that we at Glass Canvas needed so I may do separate pull requests for those later.

Why don't I attempt to give a bit of an overview, and then we can talk about how this can be split out further.  The only thing I don't want is to spend hours splitting out functionality only for it to be merged back together.

Within the glass branch, I attempted to make the individual commits 'features' (that depend on each other):
- `4212c75 updated default 404 page body`
- `c645704 New 'glass' interface for refinery` - the monster commit.  More explanation below...
- `8551fa9 Disable scroll while sorting - getting in the way`
- `5ec6613 New image upload user experience` - no media library, just straight to upload
- `94da32b New engine generator for 'glass' - also merge form generator`
- `eec91d5 'glass' test pass - many skipped & TODO`
- `1a3bdd6 New version of Devise, dummy app needs extra config` - needed this to get tests running.  I'd like advice on how to do this better
- ... about 40 more commits, we're continuing to work away at making this better, and just being open about what we're up to

So hopefully everything but `c645704 New 'glass' interface...` is fairly incremental.  Let me know if not.  And then here's a brief overview of `c645704`.

Features:
- 'invitable'        - Invite user, activates account from link in their email and create their own password
- 'glassify'         - New 'glass' look (css), getting closer to responsive design
- 'form-validation-and-errors' - New 'glass' editor using grande.js - uses contenteditable attribute
- 'glass-editor'     - AJAX forms & JS validation - instant feedback on forms and improved display of errors
- 'browser-update'   - Help users update their browser instead of supporting old browsers (for the admin interface)
- 'admin-menu-order' - Plugins dictate the order they appear in the menu - override from config - lets pick a good order that everyone is happy with
- 'page-identifier'  - Instead of a form submit redirecting to a page (found by link_url) which redirects to a separate 'thank_you' action (requiring a route, action, & html template), I found that finding a page by 'identifier' and simply redirecting to it simplified this a lot

Comments by file or dir:

1. `authentication/app/controllers/refinery/admin/users_controller.rb` - form-validation-and-errors - also set tmp password for invitable
1. `authentication/app/controllers/refinery/passwords_controller.rb` - invitable - re-use the password reset functionality
1. `authentication/app/mailers/devise/glass_mailer.rb` - invitable - different email content if user has not been accepted their invite (has not confirmed)
1. `authentication/app/models/refinery/user.rb` - invitable
1. `authentication/config/locales/en.yml` - invitable
1. `authentication/db/migrate/` - invitable
1. `authentication/config/routes.rb` - form-validation-and-errors
1. `authentication/app/views/` - glassify
1. `core/app/assets/fonts/` - glassify
1. `core/app/assets/javascripts/` - glassify & glass-editor & form-validation-and-errors - Did a lot of re-arranging here for glass-editor, see the comment at the end for more detail.  Lots of scripts are needed for both the front and admin of site.  site.js = frontend of site (sort of replaced application.js), refinery-glass.js = admin backend, kitchen-sink.js = admin is logged in and viewing front of site
1. `core/app/assets/javascripts/refinery/` - glassify - modify & remove old scripts
1. `core/app/assets/stylesheets/` - glassify & glass-editor - similar re-arranging as JS - site.css & refinery-glass.css (no kitchen-sink.css - refinery-glass.css is it)
1. `core/app/helpers/glass/misc_helper.rb` - just some asset helpers we use for hard coding AWS S3 assets - this can be removed if you don't want it
1. `core/app/views/` - glassify & glass-editor - with frontend views showing up in the admin interface, needed some fairly major re-arrangements of partials
1. `core/app/views/glass/_browser_*` - browser-update
1. `core/config/locales/en.yml` - glassify
1. `core/lib/generators/refinery/cms/templates/app/assets/stylesheets/` - glass-editor - include styles in a way that allows the admin backend to use them to edit pages with the exact same look
1. `core/lib/refinery/core/engine.rb` - glass-editor - assets re-arranged
1. `core/lib/refinery/plugin.rb` - admin-menu-order
1. `core/refinerycms-core.gemspec` - CSS dependencies
1. `core/vendor/assets/javascripts/glass/` - JS dependencies
1. `core/vendor/assets/stylesheets/glass/` - CSS dependencies
1. `images/app/models/refinery/image.rb` - image-upload - some canned geometries for previewing images when they are uploaded
1. `pages/app/controllers/refinery/admin/pages_controller.rb` - I missed this one.  It is a separate feature that I think can be moved into a separate pull request.
1. `pages/app/models/refinery/page_part.rb` - glass-editor
1. `pages/app/views/refinery/admin/pages/` - glassify & glass-editor
1. `pages/app/views/refinery/pages/` - glass-editor basic template for pages
1. `pages/db/migrate/20141230184917_add_refinery_page_identifier.rb` - page-identifier
1. `pages/db/migrate/20150330134420_add_slugify_title_to_pages.rb` - glass-editor - page slug is done in JS so it always uses custom_slug, needed a new column to know if the title and slug are 'linked' or if the custom slug should override
1. `pages/db/migrate/20150331135830_migrate_page_part_names.rb` - glass-editor - just standardized on page parts: content0, content1, ... (no need for human readable names any more, this cleans up the code)
1. `pages/db/seeds.rb` - glass-editor - same as [30]
1. `pages/lib/refinery/pages/configuration.rb` - glass-editor - same as [30]


Re-arranging js & scss assets:
```
/******************************************************************************
 *
 * site.scss          <---- BOTH ---->              refinery-glass.scss
 *                          config/_variables
 *                          glass/_manifest-back-and-frontend
 *                          _manifest-custom-back-and-frontend
 * _manifest-frontend                               glass/_manifest-backend
 *
 * Files in the 'glass' dir are intended to stay in refinery. The following are purely
 * here to be overwritten by the site / app:
 *  - config/_variables                   - customize backend without overriding
 *  - _manifest-custom-back-and-frontend  - styles for frontend, that backend will use too.
 *                                          you can also override any backend styles
 *  - _manifest-frontend                  - styles to exclude from backend, or if
 *                                          backend already includes them
 *
 ******************************************************************************/
```

So let me know your thoughts and how to proceed in splitting this up.  I've already noted on [24] that I can split that out.

-Stefan

**Comment by stefanspicer** [comment]
@anitagraham , This is the first I've heard of AMD/modular js.  I was just reading a bit and to be honest I haven't read enough to know what the benefits are.

**Comment by parndt** [comment]
@stefanspicer heads up, we just merged #2940 #2875 and a bunch of others.

**Comment by bricesanchez** [comment]
Could you rebase your branch with master ? It will be easier for us to follow your work. Thanks :)

**Comment by stefanspicer** [comment]
Thanks @bricesanchez I started work on this and then went on holiday and have been pretty swamped but it is looking like I can get to this soon.  Moving all the auth out was a pretty big change!

**Comment by bricesanchez** [comment]
What's news about your PR ?

**Comment by JulianNacci** [comment]
Pow this is so mind blowing Stefan ! Congratz !

**Comment by bricesanchez** [comment]
Closed in favor of #3071

**Pull request closed without merging**
