### PR TITLE
Allow page parts to use customised presenters

### PR DESCRIPTION
**Pull request by anitagraham**
A page part will look for a named presenter and named data.
If found it will use the presenter to present the data.

Collection_presenter is a new presenter which will present any
collection as an unordered list.

This has passed the refinerycms testing, but I haven't written tests for the new behaviour yet.

### CODE REVIEW

**Comment by anitagraham** [comment]
Close this until after 3.0 is released

**Comment by bricesanchez** [comment]
You could let it opened and tag another milestone, like 4.0

**Comment by parndt** [comment]
Well, 3.0 has been released..

**Comment by anitagraham** [comment]
I guess I can review it for need/currency and any recommended changes

**Comment by anitagraham** [comment]
I think this could be called stale. Closing.

**Pull request closed without merging**
