### PR TITLE
Italian locale amend

### PR DESCRIPTION
**Pull request by darmens**

### CODE REVIEW

**Comment by simi** [comment]
:it:  Ciao!  :it: 

Looks good to me.

@parndt speaks Italian well. Let him check this.

**Comment by darmens** [comment]
are you serious, does he? :smiley:

**Comment by ugisozols** [comment]
Couldn't resist that merge button :)

**Comment by parndt** [comment]
Molto bene!

**Comment by darmens** [comment]
@parndt sei un uomo pieno di sorprese :-)

**Pull request merged**
